#!/usr/bin/python

from optparse import make_option, OptionParser
import sys
import os

# Supported models
models = ["agency","stop"]

def upload(model,url,file,options):
	opt = ""
	if options.debug:
		opt += " --email=x.com "
	
	cmd = "appcfg.py upload_data --config_file=../gogogo-hk/gogogo/loader.py --filename=%s --url %s/remote_api --kind=gogogo_%s %s ../gogogo-hk " % (
		file,url,"%s" % model , opt)
	
	print cmd
	os.system(cmd)
	

if __name__ == "__main__":
	option_list = [
		make_option("-d", "--debug",
					action="store_true",  dest="debug",default=False),
    ]

	parser = OptionParser(option_list = option_list,usage="usage: bulkloader %s [url] [file]" % "|".join(models))
	(options , args ) = parser.parse_args()

	try:

		model = args[0]
		
		if not model in  models:
			raise ValueError('Unknown model : %s ' % model)
	
		try:
			url = args[1]
		except:
			url = "http://localhost:8000"

		try:
			file = args[2]
		except:
			file = "data/%s.txt" % model

		upload(model,url,file,options)		
		
	except Exception,v:	
		print v
		print 
		parser.print_help()
		sys.exit(-1)

	
